name: Deploy Azure Agent via 201 template
variables:
  azureConnectionName: 'MySubscription'
  resourceGroupName : 'az3037'
  organizationName : '12345'
  pool: 'AgentPool01'
  agentCount: 1
  dnsLabelPrefix: az3037skc1
  storageAccount: 'az3037skccreateazdoagent' #This needs to be globally unique
  agentFileName: 'vsts-agent-win-x64-2.183.1' #Change this if a new version is available.
  adminUsername: 'AgentAdmin'
  vmName: 'skc-3037-VM'

trigger:
- none
  # branches:
  #   include:
  #   - 'main'


stages:

- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: windows-latest
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment: Test deployment'
      inputs:
        azureSubscription: '$(azureConnectionName)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'Deploymentfiles/201-vm-winrm-windows.json'
        overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(Password) -storageAccountName $(storageAccount) -dnsLabelPrefix $(dnsLabelPrefix) -vmName $(vmName)'
        deploymentMode: 'Validation'
      enabled: false
      
- stage: Deploy
  condition:
       and(
         succeeded(),
         eq(variables['Build.SourceBranch'], 'refs/heads/main')
         )
  jobs:
  - job: deployment
    pool:
      vmImage: windows-latest
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: Delete existing ResourceGroup
      inputs:
        azureSubscription: '$(AzureConnectionName)'
        action: 'Delete'
        resourceGroupName: '$(resourceGroupName)'
      enabled: false
    - task: AzureResourceGroupDeployment@2
      displayName: Create new Azure Resources
      inputs:
        azureSubscription: '$(AzureConnectionName)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroupName)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'Deploymentfiles/201-vm-winrm-windows.json'
        overrideParameters: '-adminUsername $(adminUsername) -adminPassword $(Password) -storageAccountName $(storageAccount) -dnsLabelPrefix $(dnsLabelPrefix) -vmName $(vmName)'
        deploymentMode: 'Complete'
      enabled: true
    - task: AzureFileCopy@3
      displayName: 'Copy installation files'
      inputs:
        SourcePath: '$(Build.SourcesDirectory)/installationfiles'
        azureSubscription: '$(AzureConnectionName)'
        Destination: 'AzureVMs'
        storage: '$(storageAccount)'
        resourceGroup: '$(resourceGroupName)'
        MachineNames: 'skc-3037-VM'
        vmsAdminUserName: '$(adminUsername)'
        vmsAdminPassword: '$(Password)'
        TargetPath: 'C:\temp'
        enableCopyPrerequisites: true
      enabled: true

    - task: AzurePowerShell@4
      displayName: 'deploy custom script extension'
      inputs:
        azureSubscription: '$(AzureConnectionName)'
        ScriptType: 'FilePath'
        ScriptPath: '$(Build.SourcesDirectory)/Set-CustomScriptExtention.ps1'
        ScriptArguments: '-resourceGroupName $(resourceGroupName) -agentFileName $(agentFileName) -organizationName $(organizationName) -pat $(PAT) -pool $(pool)'
        azurePowerShellVersion: 'LatestVersion'
      enabled: true
